/**
 * Episode history — stored in localStorage so it never leaves the device.
 * Each episode records what the user reported and what the engine concluded,
 * so they can track symptoms over time and share a summary with a doctor.
 */

import { URGENCY_INFO } from '../engine/triage'

const STORAGE_KEY = 'symptomscout_history_v1'

export function loadHistory() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY)) ?? []
  } catch {
    return []
  }
}

export function saveEpisode(episode) {
  const history = loadHistory()
  history.unshift({ id: crypto.randomUUID(), savedAt: new Date().toISOString(), ...episode })
  localStorage.setItem(STORAGE_KEY, JSON.stringify(history))
  return history
}

export function deleteEpisode(id) {
  const history = loadHistory().filter((e) => e.id !== id)
  localStorage.setItem(STORAGE_KEY, JSON.stringify(history))
  return history
}

export function clearHistory() {
  localStorage.removeItem(STORAGE_KEY)
  return []
}

/** Plain-text summary of all episodes, formatted to hand to a doctor. */
export function buildDoctorSummary(history) {
  const lines = [
    'SYMPTOM HISTORY SUMMARY — generated by SymptomScout',
    'Educational tool only; not a medical diagnosis.',
    `Generated: ${new Date().toLocaleString()}`,
    '',
  ]
  for (const ep of history) {
    lines.push(`--- Episode: ${new Date(ep.savedAt).toLocaleString()} ---`)
    lines.push(`Body region: ${ep.regionLabel}`)
    lines.push(`Symptoms reported: ${ep.symptomLabels.join(', ')}`)
    lines.push(
      `Duration: ${ep.answers.durationDays} day(s) | Severity: ${ep.answers.severity}/10 | Age: ${ep.answers.age} | Fever: ${ep.answers.fever} | Recent injury: ${ep.answers.recentInjury ? 'yes' : 'no'}`,
    )
    if (ep.emergency) {
      lines.push('Result: RED FLAG reported — emergency guidance shown')
    } else {
      lines.push(`Overall guidance: ${URGENCY_INFO[ep.overallUrgency]?.label ?? ep.overallUrgency}`)
      for (const r of ep.topResults) {
        lines.push(`  • ${r.name} (${r.percent}% match, ${URGENCY_INFO[r.urgency]?.label ?? r.urgency})`)
      }
    }
    lines.push('')
  }
  return lines.join('\n')
}

/** Trigger a .txt download of the summary. */
export function downloadSummary(history) {
  const blob = new Blob([buildDoctorSummary(history)], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `symptomscout-summary-${new Date().toISOString().slice(0, 10)}.txt`
  a.click()
  URL.revokeObjectURL(url)
}
