/**
 * Episode history — stored in localStorage so it never leaves the device.
 * Each episode records what the user reported and what the engine concluded,
 * so they can track symptoms over time and share a summary with a doctor.
 *
 * Episodes may later get an `outcome` attached (see updateEpisode): whether
 * the user saw a doctor and what the real diagnosis was. Outcomes feed the
 * /insights dashboard, which produces ADVISORY suggestions for manual edits
 * to conditions.json — nothing here ever modifies scoring at runtime.
 */

import { URGENCY_INFO } from '../engine/triage'

const STORAGE_KEY = 'symptomscout_history_v1'

export function loadHistory() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY)) ?? []
  } catch {
    return []
  }
}

export function saveEpisode(episode) {
  const history = loadHistory()
  history.unshift({ id: crypto.randomUUID(), savedAt: new Date().toISOString(), ...episode })
  localStorage.setItem(STORAGE_KEY, JSON.stringify(history))
  return history
}

/**
 * Merge a partial update (e.g. { outcome }) into one episode.
 * Used by the outcome feedback form; outcomes stay editable forever
 * because users often only learn the real diagnosis days later.
 *
 * outcome shape:
 *   {
 *     sawDoctor: 'yes' | 'no' | 'not_yet',
 *     diagnosis: null | {
 *       kind: 'condition' | 'other' | 'unsure',
 *       conditionId?: string,   // when kind === 'condition' (id from conditions.json)
 *       text?: string,          // when kind === 'other' (free text)
 *     },
 *     recordedAt: ISO timestamp
 *   }
 */
export function updateEpisode(id, patch) {
  const history = loadHistory().map((e) => (e.id === id ? { ...e, ...patch } : e))
  localStorage.setItem(STORAGE_KEY, JSON.stringify(history))
  return history
}

export function deleteEpisode(id) {
  const history = loadHistory().filter((e) => e.id !== id)
  localStorage.setItem(STORAGE_KEY, JSON.stringify(history))
  return history
}

export function clearHistory() {
  localStorage.removeItem(STORAGE_KEY)
  return []
}

/** Human-readable line for an episode's outcome, shared by UI and export. */
export function describeOutcome(outcome, conditionNameById = {}) {
  if (!outcome) return null
  if (outcome.sawDoctor === 'no') return 'Did not see a doctor'
  if (outcome.sawDoctor === 'not_yet') return 'Has not seen a doctor yet'
  const d = outcome.diagnosis
  if (!d || d.kind === 'unsure') return 'Saw a doctor — diagnosis unsure'
  if (d.kind === 'other') return `Saw a doctor — diagnosis: ${d.text || 'other'}`
  return `Saw a doctor — diagnosis: ${conditionNameById[d.conditionId] ?? d.conditionId}`
}

/** Plain-text summary of all episodes, formatted to hand to a doctor. */
export function buildDoctorSummary(history, conditionNameById = {}) {
  const lines = [
    'SYMPTOM HISTORY SUMMARY — generated by SymptomScout',
    'Educational tool only; not a medical diagnosis.',
    `Generated: ${new Date().toLocaleString()}`,
    '',
  ]
  for (const ep of history) {
    lines.push(`--- Episode: ${new Date(ep.savedAt).toLocaleString()} ---`)
    lines.push(`Body region: ${ep.regionLabel}`)
    // Newer episodes carry per-symptom severity ratings; annotate when present.
    const sev = ep.symptomSeverity ?? {}
    const symptomLine = (ep.symptomIds ?? []).length === ep.symptomLabels.length && ep.symptomIds
      ? ep.symptomIds
          .map((id, i) => (sev[id] ? `${ep.symptomLabels[i]} (${sev[id]}/10)` : ep.symptomLabels[i]))
          .join(', ')
      : ep.symptomLabels.join(', ')
    lines.push(`Symptoms reported: ${symptomLine}`)
    lines.push(
      `Duration: ${ep.answers.durationDays} day(s) | Severity: ${ep.answers.severity}/10 | Age: ${ep.answers.age} | Fever: ${ep.answers.fever} | Recent injury: ${ep.answers.recentInjury ? 'yes' : 'no'}`,
    )
    if (ep.emergency) {
      lines.push('Result: RED FLAG reported — emergency guidance shown')
    } else {
      lines.push(`Overall guidance: ${URGENCY_INFO[ep.overallUrgency]?.label ?? ep.overallUrgency}`)
      for (const r of ep.topResults) {
        lines.push(`  • ${r.name} (${r.percent}% match, ${URGENCY_INFO[r.urgency]?.label ?? r.urgency})`)
      }
    }
    const outcomeLine = describeOutcome(ep.outcome, conditionNameById)
    if (outcomeLine) lines.push(`Outcome: ${outcomeLine}`)
    lines.push('')
  }
  return lines.join('\n')
}

/** Trigger a .txt download of the summary. */
export function downloadSummary(history, conditionNameById = {}) {
  const blob = new Blob([buildDoctorSummary(history, conditionNameById)], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `symptomscout-summary-${new Date().toISOString().slice(0, 10)}.txt`
  a.click()
  URL.revokeObjectURL(url)
}
